services:

  db:
    image: postgres
    restart: always
    shm_size: 128mb
    ports:
      - "5432:5432"  # ホストの5432ポートをコンテナの5432ポートにマッピング

    environment:
      POSTGRES_DB: example
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
